#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mutagen
Version  : 1.44.0
Release  : 10
URL      : https://files.pythonhosted.org/packages/96/9f/280220926cabbf4822f80e094a5190fb3df245209648e169c8bcf708697b/mutagen-1.44.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/96/9f/280220926cabbf4822f80e094a5190fb3df245209648e169c8bcf708697b/mutagen-1.44.0.tar.gz
Summary  : read and write audio tags for many formats
Group    : Development/Tools
License  : GPL-2.0 GPL-2.0+
Requires: mutagen-bin = %{version}-%{release}
Requires: mutagen-license = %{version}-%{release}
Requires: mutagen-man = %{version}-%{release}
Requires: mutagen-python = %{version}-%{release}
Requires: mutagen-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3

%description
.. image:: https://cdn.rawgit.com/quodlibet/mutagen/master/docs/images/logo.svg
   :align: center
   :width: 400px

|

Mutagen is a Python module to handle audio metadata. It supports ASF, FLAC,
MP4, Monkey's Audio, MP3, Musepack, Ogg Opus, Ogg FLAC, Ogg Speex, Ogg Theora,
Ogg Vorbis, True Audio, WavPack, OptimFROG, and AIFF audio files. All
versions of ID3v2 are supported, and all standard ID3v2.4 frames are parsed.
It can read Xing headers to accurately calculate the bitrate and length of
MP3s. ID3 and APEv2 tags can be edited regardless of audio format. It can also
manipulate Ogg streams on an individual packet/page level.

Mutagen works with Python 3.5+ (CPython and PyPy) on Linux, Windows and
macOS, and has no dependencies outside the Python standard library. Mutagen
is licensed under the GPL version 2 or later.

For more information visit https://mutagen.readthedocs.org

.. image:: https://travis-ci.org/quodlibet/mutagen.svg?branch=master
    :target: https://travis-ci.org/quodlibet/mutagen

.. image:: https://dev.azure.com/quodlibet/mutagen/_apis/build/status/quodlibet.mutagen
    :target: https://dev.azure.com/quodlibet/mutagen/_build/latest?definitionId=3

.. image:: https://codecov.io/gh/quodlibet/mutagen/branch/master/graph/badge.svg
  :target: https://codecov.io/gh/quodlibet/mutagen

%package bin
Summary: bin components for the mutagen package.
Group: Binaries
Requires: mutagen-license = %{version}-%{release}

%description bin
bin components for the mutagen package.


%package license
Summary: license components for the mutagen package.
Group: Default

%description license
license components for the mutagen package.


%package man
Summary: man components for the mutagen package.
Group: Default

%description man
man components for the mutagen package.


%package python
Summary: python components for the mutagen package.
Group: Default
Requires: mutagen-python3 = %{version}-%{release}

%description python
python components for the mutagen package.


%package python3
Summary: python3 components for the mutagen package.
Group: Default
Requires: python3-core
Provides: pypi(mutagen)

%description python3
python3 components for the mutagen package.


%prep
%setup -q -n mutagen-1.44.0
cd %{_builddir}/mutagen-1.44.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1583175305
# -Werror is for werrorists
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/mutagen
cp %{_builddir}/mutagen-1.44.0/COPYING %{buildroot}/usr/share/package-licenses/mutagen/4cc77b90af91e615a64ae04893fdffa7939db84c
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/mid3cp
/usr/bin/mid3iconv
/usr/bin/mid3v2
/usr/bin/moggsplit
/usr/bin/mutagen-inspect
/usr/bin/mutagen-pony

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mutagen/4cc77b90af91e615a64ae04893fdffa7939db84c

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/mid3cp.1
/usr/share/man/man1/mid3iconv.1
/usr/share/man/man1/mid3v2.1
/usr/share/man/man1/moggsplit.1
/usr/share/man/man1/mutagen-inspect.1
/usr/share/man/man1/mutagen-pony.1

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
