#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mutagen
Version  : 1.41.1
Release  : 1
URL      : https://files.pythonhosted.org/packages/c0/17/e1c3c18f5d637ebebcb94aa19d74c8c06925cb4ffb9f1031fe5f21a698d3/mutagen-1.41.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/c0/17/e1c3c18f5d637ebebcb94aa19d74c8c06925cb4ffb9f1031fe5f21a698d3/mutagen-1.41.1.tar.gz
Summary  : read and write audio tags for many formats
Group    : Development/Tools
License  : GPL-2.0
Requires: mutagen-bin
Requires: mutagen-python3
Requires: mutagen-license
Requires: mutagen-man
Requires: mutagen-python
BuildRequires : buildreq-distutils3

%description
.. image:: https://cdn.rawgit.com/quodlibet/mutagen/master/docs/images/logo.svg
:align: center
:width: 400px

%package bin
Summary: bin components for the mutagen package.
Group: Binaries
Requires: mutagen-license
Requires: mutagen-man

%description bin
bin components for the mutagen package.


%package license
Summary: license components for the mutagen package.
Group: Default

%description license
license components for the mutagen package.


%package man
Summary: man components for the mutagen package.
Group: Default

%description man
man components for the mutagen package.


%package python
Summary: python components for the mutagen package.
Group: Default
Requires: mutagen-python3

%description python
python components for the mutagen package.


%package python3
Summary: python3 components for the mutagen package.
Group: Default
Requires: python3-core

%description python3
python3 components for the mutagen package.


%prep
%setup -q -n mutagen-1.41.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1534859950
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/mutagen
cp COPYING %{buildroot}/usr/share/doc/mutagen/COPYING
python3 -tt setup.py build -b py3 install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/mid3cp
/usr/bin/mid3iconv
/usr/bin/mid3v2
/usr/bin/moggsplit
/usr/bin/mutagen-inspect
/usr/bin/mutagen-pony

%files license
%defattr(-,root,root,-)
/usr/share/doc/mutagen/COPYING

%files man
%defattr(-,root,root,-)
/usr/share/man/man1/mid3cp.1
/usr/share/man/man1/mid3iconv.1
/usr/share/man/man1/mid3v2.1
/usr/share/man/man1/moggsplit.1
/usr/share/man/man1/mutagen-inspect.1
/usr/share/man/man1/mutagen-pony.1

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
